/**
 * ZELREX AI SAFETY UTILITY
 * 
 * Shared reliability layer for ALL AI-generated content.
 * Import into any route that calls the Anthropic API.
 * 
 * Usage:
 *   import { validateOutput, factCheck, RELIABILITY_PROMPT } from '@/lib/aiSafety';
 *   
 *   const safeReply = validateOutput(rawReply, { checkFinancial: true });
 *   const checkedReply = await factCheck(safeReply, userMessage);
 */

import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! });

// ─── Disclaimers (exact text, reusable) ──────────────────────────

export const FINANCIAL_DISCLAIMER = `\n\n*This is strategic guidance, not financial advice. Verify all numbers independently before making financial decisions.*`;

export const CONTRACT_DISCLAIMER = `\n\n⚠️ **AI-GENERATED TEMPLATE — NOT REVIEWED BY A LAWYER.** This document was generated by Zelrex AI as a starting template. It is NOT legal advice. Have a qualified attorney review this before sending to clients or signing.`;

export const ESTIMATE_DISCLAIMER = `\n\n*Note: Numbers marked [ESTIMATED] are AI projections, not verified data. Verify independently.*`;

export const OUTREACH_DISCLAIMER = `\n\n*Prospect information was found via web search. Verify all details before reaching out.*`;

export const GUARANTEE_DISCLAIMER = `\n\n*No outcome is guaranteed. All projections are estimates based on available data.*`;

export const COMPETITOR_DISCLAIMER = `\n\n*Competitor references are based on AI knowledge, not live search. Verify independently.*`;

// ─── Reliability prompt injection ────────────────────────────────
// Append this to the system prompt of ANY Claude call that generates
// content users will act on (contracts, emails, summaries, etc.)

export const RELIABILITY_PROMPT = `
RELIABILITY RULES (NON-NEGOTIABLE):
1. NEVER fabricate data, names, companies, statistics, or sources.
2. Tag all data claims: [SEARCHED] (from web search), [ESTIMATED] (your inference), or [PATTERN] (common freelancer patterns).
3. When you don't know something, say "I don't have verified data on this" — never fill gaps with plausible-sounding fabrications.
4. Revenue projections are SCENARIOS, not predictions. Always frame as ranges, never guarantees.
5. Contracts and proposals MUST include a disclaimer that they are AI-generated and not reviewed by a lawyer.
6. When referencing a prospect's business, only state things you found via search. Do not invent details about their company, revenue, or situation.
7. If you're estimating, say so explicitly. If you're guessing, say so explicitly. Never present uncertain info as confident fact.
`;

// ─── Contract-specific prompt ────────────────────────────────────

export const CONTRACT_PROMPT = `
When generating contracts or proposals:
- Include realistic, professional terms appropriate for freelance service businesses
- Include scope of work, deliverables, timeline, payment terms, revision policy, and termination clause
- ALWAYS end with this exact disclaimer:
"⚠️ AI-GENERATED TEMPLATE — NOT REVIEWED BY A LAWYER. This document was generated by Zelrex AI as a starting template. It is NOT legal advice. Have a qualified attorney review this before sending to clients or signing."
- Do NOT include specific legal jurisdiction requirements — tell the user to have their lawyer add those
- Do NOT include non-compete clauses, arbitration clauses, or other complex legal mechanisms — those require a lawyer
`;

// ─── Outreach-specific prompt ────────────────────────────────────

export const OUTREACH_PROMPT = `
When generating outreach emails:
- Only reference details about the prospect that you found via web search or that the user provided
- Do NOT fabricate details about the prospect's business, revenue, team size, or challenges
- If you don't know something specific about the prospect, keep the email focused on what the freelancer offers instead
- Include a simple opt-out line: "Not interested? Just reply 'pass' and I won't reach out again."
- Keep emails under 120 words
- Sound human, not templated
`;

// ─── Output validation function ──────────────────────────────────

interface ValidationOptions {
  checkFinancial?: boolean;    // Check for unsourced financial claims
  checkContract?: boolean;     // Check for contract content without disclaimer
  checkGuarantee?: boolean;    // Check for guarantee language
  checkCompetitor?: boolean;   // Check for unsourced competitor claims
  checkOutreach?: boolean;     // Check for fabricated prospect details
  forceContractDisclaimer?: boolean;  // Always append contract disclaimer
  forceFinancialDisclaimer?: boolean; // Always append financial disclaimer
}

export function validateOutput(
  reply: string,
  options: ValidationOptions = {}
): string {
  let result = reply;
  const {
    checkFinancial = false, // Disabled — UI footer already says "Not financial or legal advice"
    checkContract = true,
    checkGuarantee = true,
    checkCompetitor = true,
    checkOutreach = false,
    forceContractDisclaimer = false,
    forceFinancialDisclaimer = false,
  } = options;

  // Force disclaimers if requested (for contracts, proposals)
  if (forceContractDisclaimer) {
    const hasDisclaimer = /AI-GENERATED|not reviewed by a lawyer|not legal advice|consult.*legal.*professional|AI-generated template/i.test(result);
    if (!hasDisclaimer) {
      result += CONTRACT_DISCLAIMER;
    }
  }

  if (forceFinancialDisclaimer) {
    const hasDisclaimer = /not financial advice|strategic guidance|verify.*independently|scenario estimate|not a financial advisor/i.test(result);
    if (!hasDisclaimer) {
      result += FINANCIAL_DISCLAIMER;
    }
  }

  // Check for business-relevant financial claims without provenance
  if (checkFinancial) {
    const hasBusinessFinancialClaim = /\$\d{2,}(?:,\d{3})*(?:\.\d{2})?\s*(?:\/|per|a)\s*(?:month|year|hour|project|client|week)|(?:earn|make|charge|revenue|income|profit)\s+(?:of\s+)?\$\d+|(?:pricing|price|rate|fee)\s+(?:of|at|is)\s+\$\d+/i.test(result);
    const hasProvenanceTag = /\[SEARCHED\]|\[ESTIMATED\]|\[PATTERN\]|I'm estimating|my best estimate|based on patterns|scenario estimate|I estimate|my estimate/i.test(result);
    const hasFinancialDisclaimer = /not financial advice|strategic guidance|verify.*independently|scenario estimate|not a financial advisor/i.test(result);

    if (hasBusinessFinancialClaim && !hasProvenanceTag && !hasFinancialDisclaimer) {
      result += FINANCIAL_DISCLAIMER;
    }
  }

  // Check for contract content without disclaimer
  if (checkContract) {
    const hasContractTemplate = /(?:^|\n)\s*(?:AGREEMENT|CONTRACT|SCOPE OF WORK|TERMS AND CONDITIONS|PAYMENT SCHEDULE|DELIVERABLES:)/mi.test(result);
    const hasContractDisclaimer = /AI-generated|AI-GENERATED|not reviewed by a lawyer|not legal advice|consult.*legal.*professional/i.test(result);
    if (hasContractTemplate && !hasContractDisclaimer) {
      result += CONTRACT_DISCLAIMER;
    }
  }

  // Check for guarantee language
  if (checkGuarantee) {
    const hasGuarantee = /(?:you will|you'll|I guarantee|guaranteed to)\s+(?:earn|make|get|receive|have)\b|100%\s+(?:certain|guaranteed|sure)|without a doubt you/i.test(result);
    if (hasGuarantee) {
      result += GUARANTEE_DISCLAIMER;
    }
  }

  // Check for unsourced competitor claims
  if (checkCompetitor) {
    const hasSpecificCompetitorClaim = /(?:companies? (?:like|such as)|competitors? (?:like|include|such as))\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?(?:\s+(?:charges?|offers?|earns?|makes?))/i.test(result);
    const hasSearchedTag = /\[SEARCHED\]/i.test(result);
    if (hasSpecificCompetitorClaim && !hasSearchedTag) {
      result += COMPETITOR_DISCLAIMER;
    }
  }

  return result;
}


// ─── Validate prospect claims in outreach emails ─────────────────

export function validateOutreachEmail(email: { subject: string; body: string }): { subject: string; body: string } {
  let body = email.body;

  // Check for suspiciously specific unsourced claims about the prospect
  const suspiciousClaims = /(?:your revenue|you(?:'re| are) (?:earning|making)|your (?:\d+ )?(?:employees?|team members?|staff)|you(?:'ve| have) been (?:in business|operating) for \d+)/i.test(body);
  if (suspiciousClaims) {
    // Remove or soften fabricated specifics
    body = body.replace(/(?:your revenue (?:of|is) \$[\d,]+)/gi, "your business");
    body = body.replace(/(?:your \d+ (?:employees?|team members?|staff))/gi, "your team");
  }

  return { subject: email.subject, body };
}


// ─── HAIKU FACT-CHECKER ──────────────────────────────────────────
// Runs after Opus generates a response. Uses the cheap Haiku model
// to scan for hallucinations, unsourced claims, and reliability issues.
// Cost: ~$0.001-0.003 per call. Adds ~1-2 seconds latency.

export async function factCheck(
  reply: string,
  userMessage: string
): Promise<string> {
  // Skip fact-checking for short/casual responses
  if (reply.length < 200) return reply;
  // Skip if response is clearly casual (greetings, simple acknowledgments)
  if (/^(hey|hi|hello|sure|got it|sounds good|nice|ok|understood)/i.test(reply.trim()) && reply.length < 400) return reply;

  try {
    const response = await anthropic.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 500,
      messages: [{
        role: "user",
        content: `You are a fact-checker for a business advisory AI called Zelrex. Check this AI response for reliability issues.

USER ASKED: "${userMessage.slice(0, 500)}"

AI RESPONDED:
${reply.slice(0, 3000)}

CHECK FOR THESE SPECIFIC ISSUES:
1. FABRICATED NUMBERS: Specific dollar amounts, percentages, or statistics stated as fact without [SEARCHED], [ESTIMATED], or [PATTERN] tags
2. INVENTED NAMES: Company names, person names, or tool names that might be fabricated
3. GUARANTEE LANGUAGE: Phrases like "you will earn", "guaranteed", "definitely will" 
4. FALSE MEMORY: Claims like "as we discussed" or "you mentioned" that could be fabricated recall
5. OVERCONFIDENT CLAIMS: Statements presented as certain fact that should have uncertainty disclosure

RESPOND WITH EXACTLY ONE OF:
- "CLEAN" — if no issues found
- "FLAG: [one sentence describing the issue]" — if you found a specific problem

Be conservative. Only flag clear problems, not minor phrasing issues. If the response uses provenance tags or uncertainty language properly, say CLEAN.`
      }],
    });

    const check = response.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("")
      .trim();

    if (check.startsWith("FLAG:")) {
      const issue = check.replace("FLAG:", "").trim();
      // Don't append a visible disclaimer — instead, add a subtle inline note
      // Only flag genuinely problematic content
      if (/fabricat|invent|made.?up|hallucin|fake|doesn.t exist/i.test(issue)) {
        return reply + `\n\n*⚠️ Note: ${issue} Verify this information independently.*`;
      }
      if (/guarantee|promise|certain/i.test(issue)) {
        return reply + `\n\n*Note: No outcome is guaranteed. These are estimates based on available data.*`;
      }
      // For less severe flags, just log them
      console.log(`[ZELREX FACT-CHECK] Flag: ${issue}`);
    }

    return reply;
  } catch (error) {
    // If fact-check fails, just return the original reply — never block a response
    console.warn("[ZELREX FACT-CHECK] Error (non-blocking):", error);
    return reply;
  }
}


// ═══════════════════════════════════════════════════════════════
// CODE-LEVEL ENFORCEMENT — catches rule violations the prompt missed
// 
// The prompt ASKS Claude to follow rules.
// This code ENFORCES them after the fact.
// If Claude ignores a prompt rule, this catches it.
// ═══════════════════════════════════════════════════════════════

export interface EnforcementResult {
  reply: string;
  violations: string[];
  wasModified: boolean;
  shouldRetry: boolean;  // True = violation is so bad we should re-call Claude
}

export function enforceRules(reply: string): EnforcementResult {
  let result = reply;
  const violations: string[] = [];
  let shouldRetry = false;

  // ─── 1. IDENTITY ENFORCEMENT ────────────────────────
  // Zelrex must NEVER break character. If Claude says it's an AI assistant,
  // a language model, or refers to itself as anything other than Zelrex, fix it.
  const identityBreaks = [
    /\b(?:as an AI|I'm an AI|I am an AI|as a language model|as a large language model|I'm a language model)\b/gi,
    /\b(?:I'm Claude|I am Claude|my name is Claude|I'm made by Anthropic|I was (?:created|made|built) by Anthropic)\b/gi,
    /\b(?:as an assistant|I'm just an? (?:AI|assistant|chatbot|bot))\b/gi,
    /\b(?:I don't have (?:feelings|emotions|consciousness|personal experience))\b/gi,
  ];

  for (const pattern of identityBreaks) {
    if (pattern.test(result)) {
      violations.push("IDENTITY_BREAK: Claude broke character as Zelrex");
      // Replace common identity breaks with Zelrex-appropriate language
      result = result.replace(/\bAs an AI\b/gi, "As Zelrex");
      result = result.replace(/\bI'm an AI\b/gi, "I'm Zelrex");
      result = result.replace(/\bI am an AI\b/gi, "I am Zelrex");
      result = result.replace(/\bAs a language model\b/gi, "As a business engine");
      result = result.replace(/\bAs a large language model\b/gi, "As a business engine");
      result = result.replace(/\bI'm Claude\b/gi, "I'm Zelrex");
      result = result.replace(/\bI am Claude\b/gi, "I am Zelrex");
      result = result.replace(/\bI'm just an? AI\b/gi, "I'm Zelrex");
      result = result.replace(/\bI'm just an? assistant\b/gi, "I'm Zelrex");
      result = result.replace(/\bI'm just an? chatbot\b/gi, "I'm Zelrex");
      // If the identity break is severe (multiple occurrences), flag for retry
      const breakCount = (reply.match(/\b(?:AI assistant|language model|Claude|chatbot)\b/gi) || []).length;
      if (breakCount >= 3) shouldRetry = true;
    }
  }

  // ─── 2. FORBIDDEN ADVICE ENFORCEMENT ────────────────
  // These are things Zelrex must NEVER do, regardless of what the prompt says.
  // If Claude gives specific financial/legal/tax advice, catch it.
  const forbiddenAdvice = [
    { pattern: /\b(?:you should|I recommend|I advise)\s+(?:invest(?:ing)?|put(?:ting)? (?:money|funds|savings) (?:in|into))\b/i, type: "FINANCIAL_ADVICE", fix: "*Note: This is a general observation, not investment advice. Consult a licensed financial advisor.*" },
    { pattern: /\b(?:you should|I recommend|you need to)\s+(?:form|register|incorporate|file for)\s+(?:an? )?\s*(?:LLC|corporation|S.?corp|C.?corp|sole proprietorship)\b/i, type: "LEGAL_ADVICE", fix: "*Note: Business structure is a legal decision. Consult a business attorney or CPA for advice specific to your situation.*" },
    { pattern: /\b(?:you (?:can|should)|I recommend)\s+(?:deduct|write.?off|claim)\s+(?:your|the|this)\b/i, type: "TAX_ADVICE", fix: "*Note: Tax deductions depend on your specific situation. Consult a qualified tax professional.*" },
    { pattern: /\b(?:quit|leave|resign from) your (?:job|position|employer|current role) (?:now|immediately|today|this week|right away)\b/i, type: "RECKLESS_ADVICE", fix: "*Note: Major career transitions should be planned carefully. Consider building income on the side before leaving your current position.*" },
  ];

  for (const check of forbiddenAdvice) {
    if (check.pattern.test(result)) {
      violations.push(`${check.type}: Claude gave specific advice it shouldn't`);
      // Don't remove the content — just append the appropriate disclaimer
      if (!result.includes(check.fix)) {
        result += `\n\n${check.fix}`;
      }
    }
  }

  // ─── 3. GUARANTEE ENFORCEMENT ───────────────────────
  // Hard-block guarantee language. These get rewritten, not just disclaimed.
  const guaranteePatterns = [
    { pattern: /\byou will (?:definitely|certainly|absolutely|100%) (?:earn|make|get|have|succeed)\b/gi, replacement: "based on the data, you could potentially" },
    { pattern: /\bI (?:guarantee|promise) (?:you|that)\b/gi, replacement: "based on patterns I've seen," },
    { pattern: /\b(?:guaranteed|certain|inevitable) (?:success|results?|income|revenue|outcome)\b/gi, replacement: "possible results based on similar cases" },
  ];

  for (const g of guaranteePatterns) {
    if (g.pattern.test(result)) {
      violations.push("GUARANTEE: Claude used guarantee language");
      result = result.replace(g.pattern, g.replacement);
    }
  }

  // ─── 4. OFF-TOPIC ENFORCEMENT ───────────────────────
  // Zelrex only does freelance business. If Claude starts helping with
  // homework, recipes, code debugging, or general knowledge, catch it.
  const offTopicPatterns = [
    /\b(?:here'?s? (?:a|the) recipe|ingredients?:.*(?:cup|tablespoon|teaspoon))\b/i,
    /\b(?:def |function |class |import |const |let |var |console\.log|System\.out)\b/,
    /\b(?:the (?:answer|solution) (?:is|to your (?:homework|assignment|problem)))\b/i,
  ];

  for (const pattern of offTopicPatterns) {
    if (pattern.test(result) && result.length > 200) {
      // Only flag if the response is substantially off-topic (not just mentioning code briefly)
      const offTopicScore = offTopicPatterns.filter(p => p.test(result)).length;
      if (offTopicScore >= 2) {
        violations.push("OFF_TOPIC: Response appears to be outside Zelrex's scope");
        shouldRetry = true;
      }
    }
  }

  // ─── 5. DATA LEAKAGE ENFORCEMENT ────────────────────
  // Zelrex should never expose raw user data from the intelligence system.
  const dataLeakPatterns = [
    /\bone of (?:our|my) users?\s+(?:named|called|who)\b/i,
    /\buser (?:ID|#|number)\s*(?::|is)\s*\w+/i,
    /\b(?:their|this user's) (?:email|phone|address|name) (?:is|was)\b/i,
  ];

  for (const pattern of dataLeakPatterns) {
    if (pattern.test(result)) {
      violations.push("DATA_LEAK: Response may contain user-identifying information");
      // Redact the specific match
      result = result.replace(pattern, "[redacted for privacy]");
    }
  }

  return {
    reply: result,
    violations,
    wasModified: result !== reply,
    shouldRetry,
  };
}


// ─── Full pipeline: validate + enforce + fact-check ──────────

export async function fullReliabilityPipeline(
  reply: string,
  userMessage: string,
  options: {
    checkFinancial?: boolean;
    checkContract?: boolean;
    checkGuarantee?: boolean;
    checkCompetitor?: boolean;
  } = {}
): Promise<{ reply: string; violations: string[] }> {
  // Step 1: Regex-based output validation
  let result = validateOutput(reply, options);

  // Step 2: Code-level enforcement (identity, forbidden advice, guarantees, data leaks)
  const enforcement = enforceRules(result);
  result = enforcement.reply;

  if (enforcement.violations.length > 0) {
    console.warn("[ZELREX ENFORCEMENT] Violations caught:", enforcement.violations);
  }

  // Step 3: Haiku fact-checker (async, catches hallucinations)
  result = await factCheck(result, userMessage);

  return {
    reply: result,
    violations: enforcement.violations,
  };
}